version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - mern-network

  swagger:
    build:
      context: ./swagger-final
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - ./swagger-final:/app
    command: ['node', 'index.js']

networks:
  mern-network:
    driver: bridge
