name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18] # Specify Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: backend # Checkout the repository to the 'backend' folder

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: backend # Set the working directory to 'backend'
        run: npm install # Install dependencies inside the 'backend' folder

      - name: Run tests and check coverage
        working-directory: backend # Set the working directory to 'backend'
        run: npm test -- --coverage && bash <(curl -s https://codecov.io/bash) -c -F unittests
