# name: CI
# #
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14, 16, 18] # Specify Node.js versions to test against

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test

#       - name: Run coverage
#         run: npm run coverage

#       - name: Check coverage
#         run: |
#           COVERAGE=$(grep -oP 'All files.*\K[0-9]+(?=%)' coverage/lcov-report/index.html)
#           if [ $COVERAGE -lt 80 ]; then
#             echo "Code coverage is below 80%"
#             exit 1
#           fi

#       - name: Upload coverage report
#         uses: actions/upload-artifact@v2
#         with:
#           name: coverage-report
#           path: coverage/lcov-report
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18] # Specify Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests and check coverage
        run: npm test -- --coverage && bash <(curl -s https://codecov.io/bash) -c -F unittests
